version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passowrd
      MYSQL_DATABASE: noteapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: passowrd
    volumes:
      - ".:/mydb_docker"
    ports:
      - "3307:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/noteapp"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME_DEV: noteapp
      DB_NAME_TEST: noteapp
      DB_NAME_PROD: noteapp
      DB_PASSWORD: passowrd
      DB_HOST: db
    # entrypoint: ["/app/lib/docker-entrypoint.sh"]
    # command: ["rails","server","-b","0.0.0.0","-p","3000"]
    
    #**-------------------------- ---------------------------
    # to download & build all necessary files for the new ruby project (@important Command)
    #**------------------------------------------------------
      #docker-compose run  app rails new . --force --database=mysql -skip-bundle